### ISSUE TITLE
Ruleset specific Blur/Dim and Hide Overlay setting

### ISSUE THREAD

**Issue by YourSandwich** [EVAST9919/lazer-m-vis#10]
Hey, i just wanted you to ask, to implement Rule specific Blur/Dim settings that doesent interfear with Other Osu Rulesets. And if it is possible to hide all the GUI/Overlay. Sorry if this is not the right place for these Request

Greatings

**Comment by EVAST9919** [comment]
The best I can do is to add another dim layer on top of existing one.
(And you can hide settings UI by pressing Ctrl+H)
