### ISSUE TITLE
Pausing Gameplay when loosing focus 

### ISSUE THREAD

**Issue by SuperFat-Fat** [EVAST9919/lazer-m-vis#5]
Hi ! 
I would love to be able to do something else on another window without the ruleset to pause...

I tought this was an osu's issue, but according to Peppy, the ruleset is missing something to be able to do that. Could you please add this, it would be awesome !!! 

![image](https://user-images.githubusercontent.com/51210473/80661480-15dd4300-8a8f-11ea-9979-37a68613c1cc.png)

**Comment by EVAST9919** [comment]
Small note: that basically means that this ruleset has no autoplay implementation.
Which means, that when It will be implemented - you should use it. With no autoplay it will still trigger pause (but may be I'm wrong, will look at the code tomorrow)

**Comment by SuperFat-Fat** [comment]
Oh, but, how does it works then ? Because when listening to the song, I can hear the circles being clicked, so the map is kinda played automatically, isn't it ?

**Comment by EVAST9919** [comment]
It is, but I made it just to make it like this so map can be finished (technical stuff)
Anyway: you will be able to switch to other window without auto-pause only with autoplay (which I will implement)

**Comment by EVAST9919** [comment]
@SuperFat-Fat fixed in latest release
